### ISSUE TITLE
不兼容

### ISSUE THREAD

**Issue by accfcx** [JFanZhao/feature_extraction#2]
Error:(32, 160) java: 不兼容的类型: java.util.Set<java.util.Map.Entry<java.lang.String,capture#1, 共 ? extends java.lang.Number>>无法转换为java.util.Collection<? extends java.util.Map.Entry<java.lang.String,java.lang.Number>>
jdk是9.0.4 ，请问您是哪个版本的jdk？

**Comment by JFanZhao** [comment]
JDK8的
